"""Migration

Revision ID: 4b40958ff6cf
Revises: 2e380dc230be
Create Date: 2025-06-12 10:51:48.189807

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b40958ff6cf'
down_revision: Union[str, None] = '2e380dc230be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_categories_name'), table_name='categories')
    op.create_index(op.f('ix_categories_name'), 'categories', ['name'], unique=False)
    op.create_unique_constraint('unique_category_per_user', 'categories', ['name', 'user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_category_per_user', 'categories', type_='unique')
    op.drop_index(op.f('ix_categories_name'), table_name='categories')
    op.create_index(op.f('ix_categories_name'), 'categories', ['name'], unique=True)
    # ### end Alembic commands ###
